name: uas_susulan_21312064
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.18.1
  firebase_auth: ^4.10.0
  auth: ^8.2.0+02
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/teknokrat.png